# Generated by Django 2.2 on 2019-04-25 10:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_topicposts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicposts',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='test-slug', editable=False, populate_from='title'),
        ),
    ]
