# Generated by Django 2.2 on 2019-05-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_customcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcontent',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
